language: minimal

dist: bionic

services:
 - docker

# Skip the install step. Don't `go get` dependencies. Only build with the code
# in vendor/
install: true

# Don't email me the results of the test runs.
notifications:
  email: false

# Force-enable Go modules. This will be unnecessary when Go 1.12 lands.
env:
  global:
    - GO111MODULE=on
  matrix:
    - GO_VERSION=1.13.4
      DPDK_VER=v19.08
    - GO_VERSION=1.13.4
      DPDK_VER=v18.11
    - GO_VERSION=1.12.13
      DPDK_VER=v18.11

before_install:
  - docker build --build-arg DIST=${TRAVIS_DIST} --build-arg GO_VERSION=${GO_VERSION} --build-arg DPDK_VER=${DPDK_VER} -t test-build .

# Only clone the most recent commit.
git:
  depth: 1

# script always runs to completion (set +e). If we have linter issues AND a
# failing test, we want to see both. Configure golangci-lint with a
# .golangci.yml file at the top level of your repo.
script:
  - docker run --rm test-build ./.travis.govet.sh
  - docker run --rm test-build ./.travis.golint.sh
  - docker run --rm test-build ./.travis.static.sh
  - docker run --rm test-build ./.travis.script.sh
