language: minimal

dist: focal

services:
 - docker

# Skip the install step. Don't `go get` dependencies. Only build with the code
# in vendor/
install: true

# Don't email me the results of the test runs.
notifications:
  email: false

# Force-enable Go modules. This will be unnecessary when Go 1.12 lands.
env:
  global:
    - GO111MODULE=on

before_install:
    - docker build --build-arg DPDK_DIST=${DPDK_DIST} --build-arg GO_VERSION=${GO_VERSION} -t test-build .

_test_script: &_test_script
  script:
    - docker run -w /repo -v $(pwd):/repo --rm test-build ./.travis.golint.sh
    - docker run -w /repo -v $(pwd):/repo --rm test-build ./.travis.static.sh
    - docker run -w /repo -v $(pwd):/repo --rm test-build ./.travis.govet.sh
    - docker run -w /repo -v $(pwd):/repo --rm test-build ./.travis.script.sh $TAGS

jobs:
  include:
    - env: GO_VERSION=1.16.3 DPDK_DIST=rockylinux8-v21.05 TAGS=shared
      <<: *_test_script
    - env: GO_VERSION=1.15.11 DPDK_DIST=rockylinux8-v21.05 TAGS=shared
      <<: *_test_script
  #allow_failures:
    #- env: GO_VERSION=1.13.4 DPDK_VER=v18.11 TAGS=static
    #- env: GO_VERSION=1.12.13 DPDK_VER=v18.11 TAGS=static

# Only clone the most recent commit.
git:
  depth: 1
