name: unit-testing

on:
  push:

env:
  TERM: "xterm"
  FORCE_COLOR: "1"

jobs:
  build:
    strategy:
      matrix:
        env_image:
          - nedrey/dpdk-rockylinux8:v21.11-go1.19-snf
          - nedrey/dpdk-rockylinux8:v22.11.3-go1.21.3-snf
    runs-on: ubuntu-latest
    container: ${{ matrix.env_image }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Unit Tests
        run: |
          go test -coverprofile=coverage.out -covermode=atomic ./...
      -
        name: Generate Coverage Report
        run: |
          gocover-cobertura < coverage.out > coverage.xml
      -
        name: Save Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: ./coverage.*
          retention-days: 14
      -
        name: Upload Coverage Report
        uses: codecov/codecov-action@v3
